num1=eval(input("Enter first value : "))
num2=eval(input("Enter second value : "))
print("addition of two numbers : ",num1+num2)
print("subtraction of two numbers :",num1-num2)
print("Multiplication of two numbers : ",num1*num2)
print("Division of numbers :", num1/num2)
print("Modules of numbers : ", num1%num2)
print("exponent of number : ",num1**num2)
print("floor division of numbers : ",num1//num2)
